# Generated by Django 4.0.3 on 2022-04-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='title',
            new_name='address',
        ),
    ]
