# Generated by Django 4.0.3 on 2022-04-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0004_neighbourhood_name_neighbourhood_population_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Neighbourhood_location',
        ),
        migrations.AddField(
            model_name='category',
            name='business_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='myhood.business'),
        ),
    ]
