# Generated by Django 4.0.3 on 2022-04-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0006_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hood',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myhood.neighbourhood'),
        ),
    ]
