# Generated by Django 4.0.3 on 2022-04-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0007_profile_hood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='city',
            new_name='city_address',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='address',
        ),
    ]
