# Generated by Django 4.0.3 on 2022-04-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0008_rename_city_neighbourhood_city_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
    ]
