# Generated by Django 4.0.3 on 2022-04-17 13:11

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0009_remove_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.CharField(blank=True, choices=[('school', 'school'), ('gym', 'gym'), ('gas-station', 'gas-station'), ('recreational', 'recreational'), ('religious', 'religious'), ('business', 'business'), ('shop', 'shop'), ('shopping-center', 'shopping-center'), ('residential', 'residential')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='', max_length=63),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
