# Generated by Django 4.0.3 on 2022-04-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0010_business_address_business_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='city_address',
            new_name='city',
        ),
    ]
