# Generated by Django 4.0.3 on 2022-04-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0011_rename_city_address_neighbourhood_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='city',
            new_name='city_address',
        ),
    ]
