# Generated by Django 4.0.3 on 2022-04-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0012_rename_city_neighbourhood_city_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='categories',
            field=models.CharField(blank=True, choices=[('business', 'business'), ('grocery', 'grocery'), ('gym', 'gym'), ('gas-station', 'gas-station'), ('hospital', 'hospital'), ('market', 'market'), ('recreational', 'recreational'), ('religious', 'religious'), ('residential', 'residential'), ('school', 'school'), ('shop', 'shop'), ('shopping-mall', 'shopping-mall'), ('sports', 'sports')], default='', max_length=100),
        ),
    ]
